<repositories>
    <repository>
        <id>oracle</id>
        <url>https://maven.oracle.com</url>
        <releases>
            <enabled>true</enabled>
        </releases>
        <snapshots>
            <enabled>false</enabled>
        </snapshots>
    </repository>
</repositories>
